"use client";
import { type FormEvent, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { marketplaceAdminResource } from "./resource";

const inputClass = "min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-slate-950";
export function MarketplaceAdminClient() {
  const resource = marketplaceAdminResource.bind({});
  const data = useQuery(resource.queries.data.options(undefined as never));
  const mutation = useMutation(resource.mutations.mutate.options());
  const [hotelId, setHotelId] = useState(""); const [tenantId, setTenantId] = useState("");
  const submitCategory = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); mutation.mutate({ action: "category", input: { code: String(form.get("code")), nameVi: String(form.get("nameVi")), nameEn: String(form.get("nameEn")), sortOrder: 0, isActive: true } }); };
  const submitTenant = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); mutation.mutate({ action: "tenant", input: { code: String(form.get("code")), name: String(form.get("name")), displayName: String(form.get("displayName")), owner: { email: String(form.get("email")), fullName: String(form.get("fullName")), password: String(form.get("password")) } } }); };
  if (data.isPending) return <div className="p-8">Đang tải Marketplace…</div>;
  if (data.isError || !data.data) return <div role="alert" className="p-8">Không thể tải cấu hình Marketplace.</div>;
  return <div className="space-y-8">
    <section className="grid gap-5 xl:grid-cols-2"><form onSubmit={submitCategory} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Thêm danh mục</h2><input required name="code" placeholder="RESTAURANT" className={inputClass}/><input required name="nameVi" placeholder="Nhà hàng" className={inputClass}/><input required name="nameEn" placeholder="Restaurant" className={inputClass}/><button disabled={mutation.isPending} className="min-h-11 rounded-xl bg-emerald-700 px-5 font-semibold text-white">Tạo danh mục</button></form>
    <form onSubmit={submitTenant} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Tạo Service Tenant</h2><div className="grid gap-3 sm:grid-cols-2"><input required name="code" placeholder="SPA_AN_NHIEN" className={inputClass}/><input required name="name" placeholder="Công ty An Nhiên" className={inputClass}/><input required name="displayName" placeholder="An Nhiên Spa" className={inputClass}/><input required name="fullName" placeholder="Tên người quản lý" className={inputClass}/><input required type="email" name="email" placeholder="owner@example.com" className={inputClass}/><input required minLength={8} type="password" name="password" placeholder="Mật khẩu ban đầu" className={inputClass}/></div><button disabled={mutation.isPending} className="min-h-11 rounded-xl bg-emerald-700 px-5 font-semibold text-white">Tạo Service Tenant</button></form></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Liên kết khách sạn ↔ Service Tenant</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><select aria-label="Khách sạn" className={inputClass} value={hotelId} onChange={(e) => setHotelId(e.target.value)}><option value="">Chọn khách sạn</option>{data.data.hotels.map((hotel) => <option key={hotel.id} value={hotel.id}>{hotel.name}</option>)}</select><select aria-label="Service Tenant" className={inputClass} value={tenantId} onChange={(e) => setTenantId(e.target.value)}><option value="">Chọn Service Tenant</option>{data.data.tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.serviceProfile?.displayName ?? tenant.name}</option>)}</select><button disabled={!hotelId || !tenantId || mutation.isPending} onClick={() => mutation.mutate({ action: "link", hotelId, serviceTenantId: tenantId })} className="min-h-11 rounded-xl bg-emerald-700 px-5 font-semibold text-white disabled:opacity-50">Liên kết</button></div><div className="mt-5 space-y-2">{data.data.links.map((link) => <div key={link.id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{data.data.hotels.find((hotel) => hotel.id === link.hotelId)?.name}</b> — {link.serviceTenant.serviceProfile?.displayName ?? link.serviceTenant.name} · {link.status}</div>)}</div></section>
    <section className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Danh mục ({data.data.categories.length})</h2>{data.data.categories.map((item) => <p key={item.id} className="mt-2">{item.nameVi} <span className="text-slate-500">({item.code})</span></p>)}</div><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Service Tenant ({data.data.tenants.length})</h2>{data.data.tenants.map((item) => <p key={item.id} className="mt-2">{item.serviceProfile?.displayName ?? item.name}</p>)}</div></section>
    {mutation.isError ? <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">Không thể lưu. Kiểm tra dữ liệu hoặc quyền truy cập.</p> : mutation.isSuccess ? <p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800">Đã lưu.</p> : null}
  </div>;
}
