FROM node:22-alpine

WORKDIR /app

RUN corepack enable && pnpm config set dangerouslyAllowAllBuilds true

COPY package.json ./
COPY pnpm-lock.yaml* ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev", "--hostname", "0.0.0.0"]
