CREATE TYPE "RoleType" AS ENUM ('SYSTEM_TEMPLATE', 'CUSTOM');

ALTER TABLE "Role"
ADD COLUMN "type" "RoleType" NOT NULL DEFAULT 'CUSTOM';

UPDATE "Role"
SET "type" = 'SYSTEM_TEMPLATE'
WHERE "code" IN (
  'SUPER_ADMIN',
  'VIETSAGE_OPERATION',
  'TENANT_OWNER',
  'HOTEL_OWNER',
  'HOTEL_MANAGER',
  'HOTEL_FRONTDESK',
  'HOTEL_HOUSEKEEPING',
  'HOTEL_MAINTENANCE',
  'HOTEL_FNB',
  'HOTEL_FINANCE',
  'SERVICE_STAFF'
);