ALTER TYPE "GuestRequestStatus" ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE "GuestRequestStatus" ADD VALUE IF NOT EXISTS 'CONFIRMED';
ALTER TABLE "GuestRequest" ALTER COLUMN "status" SET DEFAULT 'NEW';
ALTER TABLE "GuestRequest" ADD COLUMN IF NOT EXISTS "confirmedBy" VARCHAR(160);
ALTER TABLE "GuestRequest" ADD COLUMN IF NOT EXISTS "confirmedAt" TIMESTAMP(3);
