#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

write_if_missing() {
  local file_path="$1"
  local content="$2"

  mkdir -p "$(dirname "$file_path")"
  if [[ -e "$file_path" ]]; then
    printf 'Giữ nguyên %s (đã tồn tại)\n' "${file_path#$ROOT_DIR/}"
    return 0
  fi

  printf '%s\n' "$content" > "$file_path"
  printf 'Đã tạo %s với key rỗng\n' "${file_path#$ROOT_DIR/}"
}

POSTGRES_TEMPLATE='POSTGRES_DB=
POSTGRES_USER=
POSTGRES_PASSWORD='

AUTH_SERVICE_TEMPLATE='DATABASE_URL=
DATABASE_POOL_MAX=
DATABASE_CONNECTION_TIMEOUT_MS=
DATABASE_IDLE_TIMEOUT_MS=
DATABASE_LOCK_TIMEOUT_MS=
DATABASE_STATEMENT_TIMEOUT_MS=
DATABASE_QUERY_TIMEOUT_MS=
DATABASE_TRANSACTION_TIMEOUT_MS=
HTTP_REQUEST_TIMEOUT_MS=
HTTP_HEADERS_TIMEOUT_MS=
HTTP_KEEP_ALIVE_TIMEOUT_MS=
JWT_ACCESS_SECRET=
JWT_REFRESH_SECRET=
JWT_ACCESS_TTL=
JWT_REFRESH_TTL=
CORS_ORIGINS=
AUTHZ_ENFORCEMENT_ENABLED=
AUTHZ_STRICT_MODE=
AUTHZ_ROUTE_SYNC_ENABLED=
AUTH_ADMIN_EMAIL=
AUTH_ADMIN_NAME=
AUTH_ADMIN_PASSWORD=
AUTH_LOGIN_RATE_LIMIT_TTL_SECONDS=
AUTH_LOGIN_RATE_LIMIT_LIMIT=
AUTH_REFRESH_RATE_LIMIT_TTL_SECONDS=
AUTH_REFRESH_RATE_LIMIT_LIMIT=
LOCALMATE_KNOWLEDGE_RATE_LIMIT_TTL_SECONDS=
LOCALMATE_KNOWLEDGE_RATE_LIMIT_LIMIT=
GOOGLE_APPLICATION_CREDENTIALS=
GOOGLE_SERVICE_CATEGORY_RANGE="'\''Nhóm dịch vụ'\''!A1:Z"
GOOGLE_SERVICE_ITEM_RANGE="'\''Danh sách dịch vụ'\''!A1:Z"
TELEGRAM_BOT_TOKEN=
TELEGRAM_WEBHOOK_SECRET=
SWAGGER_ENABLED=
LOG_LEVEL=
LOCALMATE_KNOWLEDGE_API_KEY='

FRONTEND_TEMPLATE='NEXTAUTH_URL=
NEXTAUTH_SECRET=
AUTH_TRUST_HOST=
AUTH_API_BASE_URL=
NEXT_PUBLIC_AUTH_API_BASE_URL=
NEXT_PUBLIC_REALTIME_URL=
NEXT_PUBLIC_GUEST_DEFAULT_SERVICE_CATEGORY_ID=
LOCALMATE_N8N_WEBHOOK_URL=
LOCALMATE_N8N_WEBHOOK_SECRET='

N8N_TEMPLATE='N8N_ENCRYPTION_KEY=
N8N_HOST=127.0.0.1
N8N_PORT=5678
N8N_PROTOCOL=http
N8N_WEBHOOK_URL=http://127.0.0.1:5678/
N8N_EDITOR_BASE_URL=http://127.0.0.1:5678/
GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
TZ=Asia/Ho_Chi_Minh
N8N_SECURE_COOKIE=false
N8N_DIAGNOSTICS_ENABLED=false
N8N_VERSION_NOTIFICATIONS_ENABLED=false
N8N_COMMUNITY_PACKAGES_ENABLED=false
N8N_UNVERIFIED_PACKAGES_ENABLED=false
N8N_TEMPLATES_ENABLED=false
N8N_PUBLIC_API_SWAGGERUI_DISABLED=true
N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
N8N_BLOCK_ENV_ACCESS_IN_NODE=true
N8N_SSRF_PROTECTION_ENABLED=true
N8N_SSRF_ALLOWED_HOSTNAMES=host.docker.internal,auth-service
NODES_EXCLUDE=["n8n-nodes-base.executeCommand","n8n-nodes-base.localFileTrigger","n8n-nodes-base.readWriteFile"]
EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
EXECUTIONS_DATA_SAVE_ON_ERROR=all
EXECUTIONS_DATA_PRUNE=true
EXECUTIONS_DATA_MAX_AGE=168
EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
N8N_DEFAULT_BINARY_DATA_MODE=filesystem'

N8N_PRODUCTION_TEMPLATE='N8N_ENCRYPTION_KEY=
N8N_HOST=0.0.0.0
N8N_PORT=5678
N8N_PROTOCOL=http
N8N_WEBHOOK_URL=http://n8n:5678/
N8N_EDITOR_BASE_URL=http://127.0.0.1:5678/
GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
TZ=Asia/Ho_Chi_Minh
N8N_SECURE_COOKIE=false
N8N_DIAGNOSTICS_ENABLED=false
N8N_VERSION_NOTIFICATIONS_ENABLED=false
N8N_COMMUNITY_PACKAGES_ENABLED=false
N8N_UNVERIFIED_PACKAGES_ENABLED=false
N8N_TEMPLATES_ENABLED=false
N8N_PUBLIC_API_DISABLED=true
N8N_PUBLIC_API_SWAGGERUI_DISABLED=true
N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
N8N_BLOCK_ENV_ACCESS_IN_NODE=true
N8N_SSRF_PROTECTION_ENABLED=true
N8N_SSRF_ALLOWED_HOSTNAMES=auth-service
NODES_EXCLUDE=["n8n-nodes-base.executeCommand","n8n-nodes-base.localFileTrigger","n8n-nodes-base.readWriteFile"]
EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
EXECUTIONS_DATA_SAVE_ON_ERROR=all
EXECUTIONS_DATA_PRUNE=true
EXECUTIONS_DATA_MAX_AGE=168
EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
N8N_DEFAULT_BINARY_DATA_MODE=filesystem'

for env_scope in docker production; do
  write_if_missing "$ROOT_DIR/secrets/$env_scope/postgres.env" "$POSTGRES_TEMPLATE"
  write_if_missing "$ROOT_DIR/secrets/$env_scope/auth-service.env" "$AUTH_SERVICE_TEMPLATE"
  write_if_missing "$ROOT_DIR/secrets/$env_scope/frontend.env" "$FRONTEND_TEMPLATE"
done

write_if_missing "$ROOT_DIR/secrets/docker/n8n.env" "$N8N_TEMPLATE"
write_if_missing "$ROOT_DIR/secrets/production/n8n.env" "$N8N_PRODUCTION_TEMPLATE"

printf '\nCác file secrets/**/*.env đã bị gitignore. Điền giá trị thật trực tiếp trên máy local/VPS, không commit.\n'
printf 'Xem thêm: secrets/README.md\n'
