FROM node:22-alpine

WORKDIR /app

RUN corepack enable && pnpm config set dangerouslyAllowAllBuilds true

COPY package.json ./
COPY package-lock.json* ./
COPY pnpm-lock.yaml* ./

RUN pnpm install --no-frozen-lockfile

COPY . .

EXPOSE 8080

CMD ["pnpm", "start:dev"]
