"use client";
import Image from "next/image";
import { useState } from "react";
import { useGuestMarketplace } from "../queries/use-guest-marketplace";

const distance = (meters: number | null) => meters == null ? null : meters < 1000 ? `${meters} m` : `${(meters / 1000).toLocaleString("vi-VN", { maximumFractionDigits: 1 })} km`;

export function GuestMarketplace({ sessionToken }: { sessionToken: string }) {
  const [categoryId, setCategoryId] = useState<string>();
  const { categories, services, orders, order } = useGuestMarketplace(sessionToken, categoryId);
  return <section aria-labelledby="marketplace-title" className="mx-auto max-w-5xl space-y-6">
    <header><p className="text-sm font-semibold text-[#8a6a13]">Dịch vụ đã được khách sạn liên kết</p><h1 id="marketplace-title" className="mt-1 text-3xl font-bold">Marketplace địa phương</h1><p className="mt-2 text-sm text-[#5e6a62]">Đặt trực tiếp với nhà cung cấp; khoảng cách tính từ khách sạn.</p></header>
    {categories.data?.length ? <div role="group" aria-label="Lọc danh mục" className="flex gap-2 overflow-x-auto pb-2"><button className="min-h-11 rounded-full border px-4" aria-pressed={!categoryId} onClick={() => setCategoryId(undefined)}>Tất cả</button>{categories.data.map((item) => <button key={item.id} className="min-h-11 shrink-0 rounded-full border px-4 aria-pressed:bg-[#25483f] aria-pressed:text-white" aria-pressed={categoryId === item.id} onClick={() => setCategoryId(item.id)}>{item.nameVi}</button>)}</div> : null}
    {services.isPending ? <div className="grid gap-4 sm:grid-cols-2">{[1,2,3,4].map((id) => <div key={id} className="h-72 animate-pulse rounded-2xl bg-[#ece8df]" />)}</div> : services.isError ? <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800">Không thể tải Marketplace.<button className="ml-3 min-h-11 rounded-xl border px-4" onClick={() => void services.refetch()}>Thử lại</button></div> : services.data?.items.length ? <div className="grid gap-4 sm:grid-cols-2">{services.data.items.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border bg-white shadow-sm">{item.imageUrls[0] ? <Image unoptimized src={item.imageUrls[0]} alt={item.name} width={640} height={360} className="aspect-video w-full object-cover" /> : <div className="aspect-video bg-[#e9f0ec]" />}<div className="space-y-3 p-5"><div className="flex justify-between gap-3"><h2 className="font-bold">{item.name}</h2>{distance(item.distanceMeters) ? <span className="shrink-0 text-sm font-semibold text-[#25483f]">{distance(item.distanceMeters)}</span> : null}</div><p className="text-sm text-[#5e6a62]">{item.serviceTenant.serviceProfile?.displayName}</p><p className="font-bold">{Number(item.unitPrice).toLocaleString("vi-VN")} {item.currency}</p><p className="text-sm text-[#5e6a62]">Chờ dự kiến {item.waitingMinutes} phút</p><button type="button" disabled={order.isPending || item.capacityAvailable === 0} onClick={() => { if (confirm(`Đặt ${item.name} — ${Number(item.unitPrice).toLocaleString("vi-VN")} ${item.currency}? Chi phí sẽ cộng vào hóa đơn phòng.`)) order.mutate({ serviceId: item.id, quantity: 1, idempotencyKey: crypto.randomUUID() }); }} className="min-h-11 w-full rounded-xl bg-[#25483f] px-4 font-semibold text-white disabled:opacity-50">{item.capacityAvailable === 0 ? "Tạm hết lượt" : order.isPending ? "Đang đặt…" : "Đặt 1 dịch vụ"}</button></div></article>)}</div> : <div className="rounded-2xl border bg-white p-8 text-center text-[#5e6a62]">Chưa có dịch vụ phù hợp.</div>}
    {order.isSuccess ? <p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800">Đã tạo đơn {order.data.orderNumber}.</p> : order.isError ? <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">Không thể tạo đơn. Vui lòng thử lại.</p> : null}
    {orders.data?.length ? <section className="space-y-3"><h2 className="text-xl font-bold">Đơn dịch vụ của tôi</h2>{orders.data.map((item) => <div key={item.id} className="flex justify-between gap-4 rounded-xl border bg-white p-4 text-sm"><span><strong>{item.serviceNameSnapshot}</strong><br />{item.orderNumber}</span><span className="font-semibold">{item.status}</span></div>)}</section> : null}
  </section>;
}
